### ISSUE TITLE
Error: buf length isn't multiple of compact IP/PORTs

### ISSUE THREAD

**Issue by cryptninja** [ritz078/moose#74]
Media playback

`Unhandled Error
Error: buf length isn't multiple of compact IP/PORTs (6 bytes)
at Function.compact2string.multi (/Applications/moose.app/Contents/Resources/app.asar/node_modules/compact2string/index.js:22:11)
    at utPex.onMessage (/Applications/moose.app/Contents/Resources/app.asar/node_modules/ut_pex/index.js:103:24)
    at Wire._onExtended (/Applications/moose.app/Contents/Resources/app.asar/node_modules/bittorrent-protocol/index.js:554:26)
    at Wire._onMessage (/Applications/moose.app/Contents/Resources/app.asar/node_modules/bittorrent-protocol/index.js:686:21)
    at Wire._write (/Applications/moose.app/Contents/Resources/app.asar/node_modules/bittorrent-protocol/index.js:590:12)
    at doWrite (/Applications/moose.app/Contents/Resources/app.asar/node_modules/bittorrent-protocol/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/Applications/moose.app/Contents/Resources/app.asar/node_modules/bittorrent-protocol/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at Wire.Writable.write (/Applications/moose.app/Contents/Resources/app.asar/node_modules/bittorrent-protocol/node_modules/readable-stream/lib/_stream_writable.js:307:11)`

**Comment by ritz078** [comment]
Thanks for the whole stack trace. Can you tell me the steps to reproduce this ?

**Comment by ritz078** [comment]
Nevermind. I was able to reproduce this.

**Comment by ritz078** [comment]
We will need https://github.com/sindresorhus/electron-unhandled/issues/18 to fix this or we can implement the whole logic here. I will prefer the first one since that will help more people. After the filter option is present in electron-unhandled, we can just filter out this message.

**Comment by vinodf2f** [comment]
@ritz078 Created a patch for the filter option and raised a PR #268 .
Can you please review ?
